global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "tempo"
    static_configs:
      - targets: [ "example.tempo:3200" ]
  - job_name: "order"
    static_configs:
      - targets: [ "example.order:8080" ]
  - job_name: "trade"
    static_configs:
      - targets: [ "example.trade:8080" ]
  - job_name: "notification"
    static_configs:
      - targets: [ "example.notification:8080" ]
